"""
games/tic_tac_toe/launcher.py
===============================
Entry point for the macOS packaged Tic-Tac-Toe application.

When PyInstaller bundles this app, it extracts all files into a temporary
directory stored in `sys._MEIPASS` at runtime. We therefore cannot rely on
relative paths computed at development time -- every path to a bundled
resource must go through `resource_path()`.

Usage (development, run from project root):
    python3 games/tic_tac_toe/launcher.py --run_id <run_id>

Usage (after PyInstaller packaging):
    # The built app embeds the run directory you specified at build time.
    # End-users just double-click TicTacToe.app; no CLI needed.
    # If you want to expose run_id to end-users via a launcher script, see
    # games/tic_tac_toe/build_app.sh for how to wrap the PyInstaller call.

Packaging (run from project root):
    # Step 1: Install dependencies (once).
    pip install pyinstaller pygame

    # Step 2: Make the build script executable (once).
    chmod +x games/tic_tac_toe/build_app.sh

    # Step 3: Build the .app bundle.  Replace <run_id> with your training
    #         run identifier, e.g. 20240101_120000.
    ./games/tic_tac_toe/build_app.sh --run_id <run_id>

    # Output: games/tic_tac_toe/dist/TicTacToe.zip
    #   - Unzip and double-click TicTacToe.app to play.
    #   - First launch: right-click -> Open to bypass macOS Gatekeeper.
    #   - Subsequent launches: double-click as normal.
"""

import argparse
import os
import sys


# ---------------------------------------------------------------------------
# Resource-path helper
# ---------------------------------------------------------------------------

def resource_path(relative_path: str) -> str:
    """
    Resolve the absolute path to a bundled resource.

    PyInstaller extracts all `--add-data` files into a temporary folder whose
    path is stored in `sys._MEIPASS`.  When running in a normal Python
    environment (development / CI), we fall back to the current working
    directory so behaviour is identical.

    Args:
        relative_path: Path relative to the project root, e.g.
                       "runs/my_run_id" or "rl_eng/tic_tac_toe.py".

    Returns:
        Absolute path that is valid both inside and outside the bundle.
    """
    if hasattr(sys, "_MEIPASS"):
        # Running inside a PyInstaller bundle -- use the extraction temp dir.
        base = sys._MEIPASS  # type: ignore[attr-defined]
    else:
        # Running directly with the Python interpreter (development mode).
        base = os.path.abspath(".")

    return os.path.join(base, relative_path)


# ---------------------------------------------------------------------------
# Argument parsing
# ---------------------------------------------------------------------------

def parse_args() -> argparse.Namespace:
    """
    Parse command-line arguments.

    Even when the app is double-clicked from Finder, macOS may pass a
    `-psn_*` argument (Process Serial Number) to the process.  We use
    `parse_known_args` so that unknown macOS-injected flags are silently
    ignored instead of causing an error.

    Returns:
        Namespace object with attribute `run_id` (str).
    """
    parser = argparse.ArgumentParser(
        description=(
            "Launch the RL-Eng Tic-Tac-Toe pygame application. "
            "Provide the run_id that corresponds to a trained agent's "
            "state-value table stored under runs/<run_id>/."
        )
    )
    parser.add_argument(
        "--run_id",
        type=str,
        required=True,
        help=(
            "Identifier of the training run whose state-value table will be "
            "loaded by the agent.  The table must exist at "
            "runs/<run_id>/state_value_table.pkl (or whatever path your "
            "Agent.load_state_value_table() expects)."
        ),
    )

    # parse_known_args: silently drop flags we don't recognise (e.g. the
    # macOS -psn_0_XXXXXX flag that Finder injects when launching a .app
    # bundle).
    args, unknown = parser.parse_known_args()

    if unknown:
        print(
            f"[launcher] Warning: ignoring unrecognised arguments: {unknown}",
            file=sys.stderr,
        )

    return args


# ---------------------------------------------------------------------------
# Main entry point
# ---------------------------------------------------------------------------

def main() -> None:
    """
    Resolve paths and hand off control to the pygame game loop.

    Steps:
        1. Parse --run_id from the command line (or from the shell wrapper
           generated by build_app.sh).
        2. Build the run_dir path via resource_path() so it works both in
           development and inside the PyInstaller bundle.
        3. Validate that run_dir actually exists before pygame initialises,
           giving the user an actionable error message early.
        4. Instantiate TicTacToePygame and call .run(), which blocks until
           the window is closed.
    """
    args = parse_args()

    # Construct the path to the directory that holds the trained agent data.
    # resource_path() ensures this resolves correctly both during development
    # (CWD-relative) and after PyInstaller bundles everything into
    # sys._MEIPASS.
    run_dir = resource_path(os.path.join("runs", args.run_id))

    # Early validation: tell the user clearly if the run directory is missing,
    # rather than letting the game crash deep inside Agent.load_state_value_table().
    if not os.path.isdir(run_dir):
        print(
            f"[launcher] Error: run directory not found: {run_dir}\n"
            f"  Make sure you built the app with --add-data pointing to "
            f"runs/{args.run_id}, or that the directory exists in the "
            f"current working directory when running in development mode.",
            file=sys.stderr,
        )
        sys.exit(1)

    print(f"[launcher] Starting TicTacToe with run_dir: {run_dir}")

    # Import here (not at module top) so that import errors from rl_eng are
    # surfaced *after* argument validation -- this gives cleaner, more
    # actionable error messages to the developer.
    
    # Add project root to sys.path so we can import rl_eng
    project_root = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
    if project_root not in sys.path:
        sys.path.insert(0, project_root)

    # Add the current directory (games/tic_tac_toe) to sys.path to import gui.py
    game_dir = os.path.dirname(__file__)
    if game_dir not in sys.path:
        sys.path.insert(0, game_dir)

    from gui import TicTacToePygame  # noqa: PLC0415

    # Hand off to the pygame game loop.  This call blocks until the user
    # closes the window.
    TicTacToePygame(run_dir).run()


if __name__ == "__main__":
    main()
